### ISSUE TITLE
(stab <- statistical_tables("110")) command's error

### ISSUE THREAD

**Issue by degildi** [emraher/tuik#2]
Hello,
First of all, thank you for such a great effort. But I have a problem with the below command:

> (stab <- statistical_tables(110))
Error: (converted from warning) Problem with `mutate()` column `data_date`.
i `data_date = lubridate::dmy(.data$data_date, locale = "tr_TR")`.
i OS reports request to set locale to "tr_TR" cannot be honored
In addition: Warning message:
Problem with `mutate()` column `data_date`.
i `data_date = lubridate::dmy(.data$data_date, locale = "tr_TR")`.
i OS reports request to set locale to "tr_TR" cannot be honored 

Would you suggest any solution? I use Windows 10 Pro English and my locale setting is Turkey/Turkish.

**Comment by emraher** [comment]
Thanks for the feedback. I mainly use Mac with English locale so I haven't tested the package on Windows. After your feedback I installed a virtual Windows machine and tested the package. I added a quick fix (https://github.com/emraher/tuik/commit/6625ba946eb62d81996a4bf38aabeaa2e48ca0a1).

This is the system I have.

```
> Sys.info()
          sysname           release           version          nodename 
        "Windows"          "10 x64"     "build 19043" "DESKTOP-291NG4I" 
          machine             login              user    effective_user 
         "x86-64"             "eer"             "eer"             "eer" 
```


This is the locale.

```
> Sys.getlocale()
[1] "LC_COLLATE=Turkish_Turkey.1254;LC_CTYPE=Turkish_Turkey.1254;LC_MONETARY=Turkish_Turkey.1254;LC_NUMERIC=C;LC_TIME=Turkish_Turkey.1254"
```


This is the result.
```
> (stab <- tuik::statistical_tables("110"))
# A tibble: 52 x 5
   theme_name      theme_id data_name                          data_date  datafile_url
   <chr>           <chr>    <chr>                              <date>     <chr>       
 1 Adalet ve Seçim 110      Hükümlü ve Tutuklu Sayısı          2021-11-02 http://data~
 2 Adalet ve Seçim 110      Suç Türü ve Medeni Durumuna Göre ~ 2021-11-02 http://data~
 3 Adalet ve Seçim 110      İBBS, 1. Düzeyde, Suç Türü ve Suç~ 2021-11-02 http://data~
 4 Adalet ve Seçim 110      İBBS 3. Düzeyde, Daimi İkametgah ~ 2021-11-02 http://data~
 5 Adalet ve Seçim 110      Suç Türü ve Uyruğuna Göre Ceza İn~ 2021-11-02 http://data~
 6 Adalet ve Seçim 110      Suç Türü ve Eğitim Durumuna Göre ~ 2021-11-02 http://data~
 7 Adalet ve Seçim 110      Suç Türü ve Suçun İşlendiği Yaş G~ 2021-11-02 http://data~
 8 Adalet ve Seçim 110      İBBS, 3. Düzeyde, Suç Türü ve Suç~ 2021-11-02 http://data~
 9 Adalet ve Seçim 110      Suç Türü ve Suçun İşlendiği Andak~ 2021-11-02 http://data~
10 Adalet ve Seçim 110      İBBS 3. Düzeyde, Suçun İşlendiği ~ 2021-11-02 http://data~
# ... with 42 more rows
```

**Can you please check again with this updated version of the package and provide feedback again? Thanks in advance.**

**Comment by degildi** [comment]
Thank you very much.
It is working for Windows 10. I have the same Sys.Info() and Sys.getlocale() result.
Best Regards,
